# -*- coding: utf-8 -*-
"""phase 2: crawl image.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wM1gU1qEtpFBONOi3pC8FXT9y-TEfWSE
"""

import re
import requests
from bs4 import BeautifulSoup

# lảm mỗi lần một hãng để tránh trục trặc


urls = ['https://tiki.vn/search?q=lock%20and%20lock&ref=searchBar']
base_url = 'https://tiki.vn'

#lấy tên các trang muốn download hình ảnh về 

i = True
while(i):
  with requests.get(urls[-1]) as r:
    soup = BeautifulSoup(r.text)
    if soup.find('a', {'class': 'next'}):
      elm = soup.find('a', {'class': 'next'})
      next_page_link = base_url + elm['href']
      urls.append(next_page_link)
      print(next_page_link)
    else:
      i = False
      break

#tạo dataframe chưa tên web

import pandas as pd
df = pd.DataFrame(data={"url": urls})
#len(df)

# download hình từ dataframe

for i in range(len(df)):
  print(df.url[i])
  site = df.url[i]
  response = requests.get(site)
  soup = BeautifulSoup(response.text, 'html.parser')
  
  
  img_tags = soup.find_all('img')
  #img_tags
  img_tags[0]['src']

  urls = []
  for i in range(len(img_tags)):
    if img_tags[i].has_attr('src'):
      urls.append(img_tags[i]['src'])

  for url in urls:
    
    filename = re.search(r'/([\w_-]+[.](jpg|gif|png))$', url)
    if filename:
      with open("/content/drive/My Drive/mmdetection/images_tiki_false/lockandlock"+filename.group(0), 'wb') as f:
        if 'http' not in url:
          url = '{}{}'.format(site, url)
        response = requests.get(url)
        f.write(response.content)

print("done")



